name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          config_timezone: Asia/Beijing
          base: header, activity, community, repositories, metadata
          plugin_isocalendar: yes
          plugin_languages: yes
          plugin_habits: yes
          plugin_projects: yes
          plugin_achievements: yes
          plugin_repositories: yes
          plugin_anilist: yes
          plugin_anilist_medias: anime
          plugin_anilist_sections: favorites, watching
          plugin_anilist_user: rinshimizu
          output_action: commit
          committer_branch: metrics-renders
          committer_message: "chore: update metrics"
          retries: 3
          retries_delay: 300
          optimize: css, xml
          
          
