name: Metrics-right
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics-right.svg
          token: ${{ secrets.METRICS_TOKEN }}
          config_timezone: Canada/Eastern
          template: classic
          # base: header, activity, community, repositories, metadata
          config_display: regular
          plugin_achievements: yes
          plugin_achievements_display: detailed
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: C
          
          # plugin_habits: yes
          # plugin_habits_charts_type: classic
          # plugin_habits_days: 14
          # plugin_habits_facts: yes
          # plugin_habits_from: 200
          # plugin_habits_languages_limit: 8
          # plugin_habits_languages_threshold: 0%
          # plugin_isocalendar: yes
          # plugin_isocalendar_duration: half-year
          # plugin_languages: yes
          # plugin_languages_analysis_timeout: 15
          # plugin_languages_analysis_timeout_repositories: 7.5
          # plugin_languages_categories: markup, programming
          # plugin_languages_colors: github
          # plugin_languages_limit: 8
          # plugin_languages_recent_categories: markup, programming
          # plugin_languages_recent_days: 14
          # plugin_languages_recent_load: 300
          # plugin_languages_sections: most-used
          # plugin_languages_threshold: 0%
          # plugin_lines: yes
          # plugin_lines_history_limit: 1
          # plugin_lines_repositories_limit: 4
          # plugin_lines_sections: base
          
          plugin_leetcode: yes
          plugin_leetcode_user: rei-smz
          plugin_leetcode_sections: solved, skills, recent
          
          # plugin_anilist: yes
          # plugin_anilist_medias: anime
          # plugin_anilist_sections: favorites, characters
          # plugin_anilist_user: rinshimizu
          # plugin_steam_token: ${{ secrets.STEAM_TOKEN }}
          
          plugin_steam: yes
          plugin_steam_user: "76561198138746288"
          plugin_steam_sections: player, recently-played, most-played
          output_action: commit
          committer_branch: metrics-renders
          committer_message: "chore: update metrics right"
          retries: 3
          retries_delay: 300
          optimize: css, xml
          
          
